definitions:
  app.Pager:
    properties:
      page:
        type: integer
      page_size:
        type: integer
      total_rows:
        type: integer
    type: object
  model.SwaggerTag:
    properties:
      list:
        items:
          $ref: '#/definitions/model.Tag'
        type: array
      pager:
        $ref: '#/definitions/app.Pager'
    type: object
  model.Tag:
    properties:
      created_by:
        description: 创建人
        type: string
      created_on:
        description: 创建时间
        type: integer
      deleted_on:
        description: 删除时间
        type: integer
      id:
        type: integer
      is_del:
        type: integer
      modified_by:
        description: 修改人
        type: string
      modified_on:
        description: 修改时间
        type: integer
      name:
        type: string
      state:
        type: string
    type: object
info:
  contact: {}
paths:
  /api/v1/tags:
    post:
      parameters:
      - description: 标签名称
        in: body
        maxLength: 100
        minLength: 3
        name: name
        required: true
        schema:
          type: string
      - default: 1
        description: 状态
        enum:
        - 0
        - 1
        in: body
        name: state
        schema:
          type: integer
      - description: 创建者
        in: body
        maxLength: 100
        minLength: 3
        name: created_by
        required: true
        schema:
          type: string
      produces:
      - application/json
      responses:
        "200":
          description: 成功
          schema:
            $ref: '#/definitions/model.SwaggerTag'
      summary: 新增标签
swagger: "2.0"
